const certifications = [
  {
    title: "Gemini Certified Faculty",
    issuer: "Google for Education",
    year: "2026",
    icon: "🤖",
    color: "from-blue-600 to-cyan-500",
    type: "Certification",
  },
  {
    title: "Google Certified Educator Level 1",
    issuer: "Google for Education",
    year: "2026",
    icon: "🎓",
    color: "from-green-600 to-emerald-500",
    type: "Certification",
  },
  {
    title: "Deloitte Australia – Data Analytics Job Simulation",
    issuer: "Forage",
    year: "2025",
    icon: "📊",
    color: "from-indigo-600 to-blue-500",
    type: "Certification",
  },
  {
    title: "How to Optimize Your Instagram Account",
    issuer: "Coursera Project Network",
    year: "2025",
    icon: "📱",
    color: "from-pink-600 to-rose-500",
    type: "Certification",
  },
  {
    title: "Lead Trainer – Power BI Master Class",
    issuer: "Infinity Code Nexus",
    year: "2026",
    icon: "👨‍🏫",
    color: "from-yellow-500 to-orange-500",
    type: "Professional Achievement",
  },
  {
    title: "Lead Trainer – Power BI Internship Program",
    issuer: "Infinity Code Nexus",
    year: "2026",
    icon: "🏅",
    color: "from-purple-600 to-pink-500",
    type: "Professional Achievement",
  },
];